server:
  port: 8082

spring:
  application:
    name: auth-service

  cloud:
    config:
      import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  spring:
    datasource:
      url: jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1
      driver-class-name: org.h2.Driver
      username: sa
      password:
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true
      show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console


jwt:
  private-key-path: classpath:keys/private.pem
  public-key-path: classpath:keys/public.pem
  expiration-ms: 600000  # 1시간

