server:
  port: 8000

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Eureka에 등록된 서비스 자동 인식
#      routes:
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/users/**
#        - id: order-service
#          uri: lb://order-service
#          predicates:
#            - Path=/orders/**

  config:
    import: optional:xconfigserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761
